import { Outlet } from 'react-router-dom';
import { Provider } from 'react-redux';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { store } from '../redux/store';
import './globals.css';

// Import Google fonts directly using CSS import instead of Next.js font loader
import '@fontsource/geist-sans';
import '@fontsource/geist-mono';

// Create a client for React Query
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 60 * 1000, // 1 minute
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Core Sample</title>
        <meta name="description" content="Generated by create Vite" />
      </head>
      <body className="font-geist-sans antialiased">
        {/* Redux Provider for global state management */}
        <Provider store={store}>
          {/* React Query Provider for API data fetching */}
          <QueryClientProvider client={queryClient}>
            {/* React Router Outlet for rendering nested routes */}
            <Outlet />
          </QueryClientProvider>
        </Provider>
      </body>
    </html>
  );
}